Add Ghostery navbar
whotracksme/whotracks.me pull request #322
Opened 2023-06-21 14:32 UTC by smalluban

Fixes https://github.com/ghostery/journal/issues/124

2023-06-21 16:00 UTC, philipp-classen approved these changes

2023-06-22 10:32 UTC, kalinme requested changes
2 changes needed:
- Update typography on desktop and mobile (headers and body) https://www.figma.com/file/l6IQBtlomzWarTJRtBtuE2/WhoTracks.Me?type=design&node-id=218%3A2185&mode=design&t=1IEUtXD8Y3AvfJkZ-1
- Update spacings in the panel to keep the same for expanded and collapsed versions (desktop and mobile): https://www.figma.com/file/l6IQBtlomzWarTJRtBtuE2/WhoTracks.Me?type=design&node-id=243%3A2167&mode=design&t=1IEUtXD8Y3AvfJkZ-1

2023-06-22 10:35 UTC, kalinme requested changes
2 changes needed:
- Update typography on desktop and mobile (headers and body) https://www.figma.com/file/l6IQBtlomzWarTJRtBtuE2/WhoTracks.Me?type=design&node-id=218%3A2185&mode=design&t=1IEUtXD8Y3AvfJkZ-1
- Update spacings in the panel to keep the same for expanded and collapsed versions (desktop and mobile): https://www.figma.com/file/l6IQBtlomzWarTJRtBtuE2/WhoTracks.Me?type=design&node-id=243%3A2167&mode=design&t=1IEUtXD8Y3AvfJkZ-1

2023-06-22 15:42 UTC, philipp-classen approved these changes

2023-06-22 16:02 UTC, kalinme approved these changes

2023-06-22 16:07 UTC, kalinme requested changes
Decrease font size of Hide/Show more button to 13px: https://www.figma.com/file/l6IQBtlomzWarTJRtBtuE2/WhoTracks.Me?type=design&node-id=243%3A2167&mode=design&t=kSip4N0W6FFDryho-1

2023-06-23 09:32 UTC, philipp-classen approved these changes

2023-06-23 09:36 UTC, merged